CREATE TABLE BRANDS (
    ID   BIGINT      NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PRICES (
    ID         BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   BIGINT        NOT NULL,
    START_DATE TIMESTAMP     NOT NULL,
    END_DATE   TIMESTAMP     NOT NULL,
    PRICE_LIST BIGINT        NOT NULL,
    PRODUCT_ID BIGINT        NOT NULL,
    PRIORITY   INT           NOT NULL,
    PRICE      DECIMAL(10,2) NOT NULL,
    CURR       CHAR(3)       NOT NULL,
    CONSTRAINT FK_PRICES_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID),
    CONSTRAINT CK_PRICES_START_BEFORE_END CHECK (START_DATE <= END_DATE)
);

ALTER TABLE PRICES ADD CONSTRAINT CK_PRICES_NO_OVERLAP_WITH_SAME_PRIORITY CHECK (NOT EXISTS (
    SELECT 1
    FROM PRICES OTHER
    WHERE OTHER.BRAND_ID = PRICES.BRAND_ID
      AND OTHER.PRODUCT_ID = PRICES.PRODUCT_ID
      AND OTHER.PRIORITY = PRICES.PRIORITY
      AND OTHER.START_DATE <= PRICES.END_DATE
      AND PRICES.START_DATE <= OTHER.END_DATE
      AND OTHER.ID <> PRICES.ID
));

CREATE INDEX IDX_PRICES_LOOKUP ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
